# Generated by Django 4.1.7 on 2023-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.BooleanField(default=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.BooleanField(null=True),
        ),
    ]
