# Generated by Django 4.1.7 on 2023-06-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0006_alter_account_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('savings', 'savings'), ('current', 'current'), ('golden', 'golden')], default='savings', max_length=10)),
                ('debt', models.BooleanField(default=False)),
                ('display_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfapp.account')),
            ],
        ),
    ]
