# Generated by Django 4.1.7 on 2023-06-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0007_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='real_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
