# Generated by Django 4.1.7 on 2023-06-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0008_money_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='display_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drfapp.account'),
        ),
    ]
