# Generated by Django 4.1.7 on 2023-06-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0009_alter_money_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='display_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='drfapp.account'),
        ),
    ]
